POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "nombre": "Miel de abejas",
    "precio": 4000,
    "stock": 25,
    "categoria": ["Producto animal", "Apicultura"]
}
###
put http://localhost:3000/api/productos/id
Content-Type: application/json

{
    "precio": 3000000,
    "stock": 30,
}

delete http://localhost:3000/api/productos/id